export const COMPANY_CREATE_STRINGS = {
  buttonLabel: 'Добавить компанию',
  dialogTitle: 'Новая компания',
  dialogDescription: 'Заполните информацию о компании и вакансии',
  submitButton: 'Добавить',
  cancelButton: 'Отмена',
  successMessage: 'Компания добавлена',
  errorMessage: 'Не удалось добавить компанию',
  fields: {
    name: { label: 'Название компании', placeholder: 'Т-Банк' },
    position: { label: 'Должность', placeholder: 'Senior Frontend Developer' },
    status: { label: 'Этап' },
    website: { label: 'Сайт компании', placeholder: 'https://tinkoff.ru' },
    jobUrl: { label: 'Ссылка на вакансию', placeholder: 'https://hh.ru/vacancy/...' },
    source: { label: 'Источник' },
    salaryMin: { label: 'Зарплата от', placeholder: '300000' },
    salaryMax: { label: 'Зарплата до', placeholder: '500000' },
    salaryCurrency: { label: 'Валюта' },
    techStack: { label: 'Стек технологий', placeholder: 'React, TypeScript, Next.js' },
    notes: { label: 'Заметки', placeholder: 'Интересный продукт, хорошая команда...' },
    priority: { label: 'Приоритет' },
  },
  sourceOptions: {
    hh: 'hh.ru',
    linkedin: 'LinkedIn',
    referral: 'Реферал',
    telegram: 'Telegram',
    company_site: 'Сайт компании',
    other: 'Другое',
  },
  priorityOptions: {
    0: 'Без приоритета',
    1: 'Низкий',
    2: 'Средний',
    3: 'Высокий',
  },
} as const;
